### ISSUE TITLE
Is there a conflict between py6s and python3.7？

### ISSUE THREAD

**Issue by lwk1542** [robintw/Py6S#48] opened 2019-05-25 13:56 UTC

**Comment by robintw** [comment] 2019-05-25 16:36
No, as far as I'm aware, Py6S works fine on Python 3.7.

Are you getting some errors? Or difficulty installing? If you provide some more details then I can look into it for you.

**Comment by jacobbieker** [comment] 2019-06-19 14:00
On my machine, using Anaconda, it downgrades to Python 3.6 if you try installing it in a Python 3.7 environment.

**Comment by robintw** [comment] 2019-06-19 18:37
Ah yes, I've just tried this and had the same problem.

It's actually not caused by Py6S, but one of its dependencies, Pysolar. Py6S depends on Pysolar v0.6, as that is the latest version that is compatible with both python 2 and python 3, but there don't seem to be any builds available on conda for Pysolar 0.6 for Python 3.7 (probably because the last time a build was done for v0.6 Python 3.7 hadn't been released).

I've raised an issue on the Pysolar conda-forge feedstock (https://github.com/conda-forge/pysolar-feedstock/issues/9) to ask them if they can run a new 'noarch' build for Pysolar 0.6 (this will then be compatible with all python versions), and I'll let you know if there is any progress there.

In the meantime, you can install Py6S using pip (from which Pysolar 0.6 will be installed that will work with Python 3.7) and then just install the underlying 6S model from conda (`conda install -c conda-forge sixs`)

**Comment by robintw** [comment] 2019-06-20 08:38
This has now been fixed (far quicker than I expected). A version of Pysolar 0.6 that supports all Python versions has been released, so you should be able to install Py6S in a Python 3.7 environment without downgrading Python.

Let me know if you have any other problems.

**Closed by robintw** 2019-06-20 08:38 UTC
